#!/bin/sh

# grab our firstboot script
/usr/bin/curl -o /srv/firstboot https://shaos.ws/firstboot
chmod +x /srv/firstboot

# create a service that will run our firstboot script
cat > /etc/init.d/firstboot <<EOF
#!/bin/sh

### BEGIN INIT INFO
# Provides:        firstboot
# Required-Start:  $networking
# Required-Stop:   $networking
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: A script that runs once
# Description: A script that runs once
### END INIT INFO

cd /srv ; /usr/bin/nohup sh -x /srv/firstboot &

EOF

# install the firstboot service
chmod +x /etc/init.d/firstboot
update-rc.d firstboot defaults

echo "finished postinst"